"""
Download 1-minute aggregate bars for option contracts listed in a contract manifest,
with split-adjusted prices (adjusted=True). Merges with underlying OHLCV data and
computes days-to-expiry and moneyness.

Reads the manifest from contracts_manifest_<year>.csv (generated by options_chain_discover.py)
and downloads aggregates for each contract via the Massive REST API.

Output layout (default):
    data/options/chains/<year>/<ticker>_<year>_chains.csv

With --output:
    <output>/options/chains/<year>/<ticker>_<year>_chains.csv

Staging: writes to processing/<ticker>_<year>_chains.csv, renames on success.

Usage:
    python scripts/options/options_chain_download.py --tickers AAPL --year 2025
    python scripts/options/options_chain_download.py --tickers AAPL,NVDA --year 2025 --resume
    python scripts/options/options_chain_download.py --tickers AAPL --year 2025 --output data/combined
    python scripts/options/options_chain_download.py --tickers_file data/universes/2025/combined_unique.csv --year 2025 --spawn 50
"""

import argparse
import csv
import datetime
import gzip
import json
import logging
import os
import sys
import time
from pathlib import Path

from dotenv import load_dotenv

env_path = Path(__file__).resolve().parent.parent.parent / ".env"
load_dotenv(env_path)

api_key = os.getenv("APIKEY")
if not api_key:
    raise ValueError("APIKEY not found in .env")
os.environ["MASSIVE_API_KEY"] = api_key

from massive import RESTClient
from massive.rest.models import Agg

SCRIPT_NAME = Path(__file__).resolve().stem

AGGREGATE_MAP = {
    "1sec": (1, "second", "1sec"),
    "1min": (1, "minute", "1min"),
    "5min": (5, "minute", "5min"),
    "15min": (15, "minute", "15min"),
    "1H": (1, "hour", "1H"),
    "4H": (4, "hour", "4H"),
    "1D": (1, "day", "1D"),
}

CHAIN_HEADERS = [
    "ticker",
    "timestamp",
    "contract_symbol",
    "strike",
    "call_put",
    "expiry",
    "days_to_expiry",
    "expiry_type",
    "open",
    "high",
    "low",
    "close",
    "volume",
    "vwap",
    "transactions",
    "underlying_price",
    "moneyness",
    "intrinsic_value",
    "extrinsic_value",
    "mid",
    "bid",
    "ask",
    "spread",
    "implied_volatility",
    "delta",
    "gamma",
    "theta",
    "vega",
]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Download 1min options chain bars from the Massive REST API"
    )
    parser.add_argument("--tickers", type=str, default=None,
                        help="Comma-separated ticker symbols (e.g. AAPL,TSLA,NVDA)")
    parser.add_argument("--tickers_file", type=str, default=None,
                        help="Path to CSV with ticker list (header 'ticker')")
    parser.add_argument("--year", type=str, required=True,
                        help="Year or year range (e.g. 2025 or 2022-2025)")
    parser.add_argument("--aggregate", choices=list(AGGREGATE_MAP.keys()),
                        default="1min",
                        help="Aggregate window size (default: 1min)")
    parser.add_argument("--manifest", type=str, default=None,
                        help="Path to contract manifest CSV. Default: data/options/chains/contract_manifest_<year>.csv")
    parser.add_argument("--output", type=str, default=None,
                        help="Base output directory (default: data/)")
    parser.add_argument("--resume", action="store_true",
                        help="Skip tickers that already have a non-empty output file")
    parser.add_argument("--delay", type=float, default=0.1,
                        help="Sleep seconds between API calls (default: 0.1)")
    parser.add_argument("--no_rename", action="store_true", default=False,
                        help="Leave output in processing/ directory (used internally by parallel runner)")
    return parser.parse_args()


def clean_ticker(raw: str) -> str:
    return raw.strip().upper().split("-")[0]


def load_tickers(args) -> list[str]:
    tickers = []
    if args.tickers:
        tickers.extend(clean_ticker(t) for t in args.tickers.split(",") if t.strip())
    if args.tickers_file:
        with open(args.tickers_file) as f:
            reader = csv.DictReader(f)
            for row in reader:
                t = row.get("ticker", "").strip()
                if t:
                    tickers.append(clean_ticker(t))
    if not tickers:
        raise SystemExit("Error: specify --tickers or --tickers_file")
    return list(dict.fromkeys(tickers))


def load_manifest(manifest_path: str, ticker: str, year: str) -> list[dict]:
    contracts = []
    if not os.path.exists(manifest_path):
        raise SystemExit("Error: manifest not found: %s" % manifest_path)
    with open(manifest_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            c_ticker = row.get("ticker", "").strip().upper()
            if c_ticker != ticker.upper():
                continue
            exp_str = row.get("expiration_date", "").strip()
            if not exp_str:
                continue
            try:
                expiry = datetime.date.fromisoformat(exp_str)
            except ValueError:
                continue
            contracts.append({
                "ticker": ticker,
                "contract_symbol": row["contract_symbol"],
                "strike": float(row["strike"]),
                "expiration_date": exp_str,
                "expiry": expiry,
                "contract_type": row.get("contract_type", ""),
                "shares_per_contract": row.get("shares_per_contract", "100"),
            })
    return contracts


def classify_expiry_type(expiry: datetime.date, dte: int) -> str:
    if expiry.weekday() == 4:
        if 15 <= expiry.day <= 21:
            return "Monthly"
        return "Weekly"
    if dte <= 7:
        return "Weekly"
    return "Monthly"


def load_underlying_cache(underlying_dir: Path, ticker: str, year: str) -> dict[str, float]:
    cache: dict[str, float] = {}
    local_tz = datetime.timezone(datetime.timedelta(hours=8))  # AWST
    for ext in (".csv", ".csv.gz"):
        path = underlying_dir / f"{ticker}_{year}_1min{ext}"
        if path.exists():
            opener = gzip.open if ext == ".csv.gz" else open
            with opener(path, "rt", errors="replace") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    ts = row.get("timestamp", "")
                    close_val = row.get("close", "")
                    if ts and close_val:
                        try:
                            dt_local = datetime.datetime.fromisoformat(ts)
                            dt_utc = dt_local.replace(tzinfo=local_tz).astimezone(datetime.timezone.utc)
                            ts_utc = dt_utc.strftime("%Y-%m-%dT%H:%M:%S+00:00")
                            cache[ts_utc] = float(close_val)
                        except (ValueError, KeyError):
                            pass
            break
    return cache


def output_path(ticker: str, year: str, agg: str, output_dir: str | None = None, subdir: str | None = None) -> Path:
    base = Path(output_dir) if output_dir else Path("data")
    p = base / "options" / "chains" / AGGREGATE_MAP[agg][2] / year
    if subdir:
        p = p / subdir
    return p / f"{ticker}_{year}_{AGGREGATE_MAP[agg][2]}_chains.csv"


def is_ticker_complete(ticker: str, year: str, agg: str, output_dir: str | None = None) -> bool:
    p = output_path(ticker, year, agg, output_dir)
    if not p.exists() or p.stat().st_size == 0:
        return False
    with open(p) as f:
        return sum(1 for _ in f) > 1


def download_contract_aggs(client: RESTClient, contract: dict, from_date: str,
                           to_date: str, agg: str, underlying_cache: dict[str, float],
                           writer, delay: float, logger: logging.Logger) -> int:
    written = 0
    strike = contract["strike"]
    symbol = contract["contract_symbol"]
    ticker = contract["ticker"]
    call_put = "C" if contract.get("contract_type", "").lower() == "call" else "P"
    expiry = contract["expiry"]
    expiry_str = contract["expiration_date"]
    is_call = call_put == "C"

    multiplier, timespan, _ = AGGREGATE_MAP[agg]

    # Forward-fill state per contract
    last_close = None
    last_underlying = None

    try:
        for agg_bar in client.list_aggs(
            symbol, multiplier, timespan, from_date, to_date,
            adjusted=True, limit=50000,
        ):
            if not isinstance(agg_bar, Agg) or agg_bar.timestamp is None:
                continue
            try:
                dt = datetime.datetime.fromtimestamp(agg_bar.timestamp / 1000, tz=datetime.timezone.utc)
                ts_str = dt.strftime("%Y-%m-%dT%H:%M:%S+00:00")
            except (ValueError, OSError):
                continue

            dte = max(0, (expiry - dt.date()).days)
            expiry_type = classify_expiry_type(expiry, dte)

            close_val = float(agg_bar.close) if agg_bar.close is not None else last_close
            if close_val is not None:
                last_close = close_val

            underlying_price = underlying_cache.get(ts_str) or last_underlying
            if underlying_price:
                last_underlying = underlying_price

            moneyness = ""
            intrinsic_value = ""
            extrinsic_value = ""
            if underlying_price and underlying_price > 0:
                moneyness = str(round((strike - underlying_price) / underlying_price, 6))
                if is_call:
                    intrinsic = max(underlying_price - strike, 0.0)
                else:
                    intrinsic = max(strike - underlying_price, 0.0)
                intrinsic_value = str(round(intrinsic, 4))
                if close_val is not None:
                    extrinsic_value = str(round(max(close_val - intrinsic, 0.0), 4))

            close_str = str(close_val) if close_val is not None else ""
            und_str = str(underlying_price) if underlying_price else ""

            writer.writerow({
                "ticker": ticker,
                "timestamp": ts_str,
                "contract_symbol": symbol,
                "strike": str(strike),
                "call_put": call_put,
                "expiry": expiry_str,
                "days_to_expiry": str(dte),
                "expiry_type": expiry_type,
                "open": str(agg_bar.open) if agg_bar.open is not None else "",
                "high": str(agg_bar.high) if agg_bar.high is not None else "",
                "low": str(agg_bar.low) if agg_bar.low is not None else "",
                "close": close_str,
                "volume": str(agg_bar.volume) if agg_bar.volume is not None else "",
                "vwap": str(agg_bar.vwap) if agg_bar.vwap is not None else "",
                "transactions": str(agg_bar.transactions) if agg_bar.transactions is not None else "",
                "underlying_price": und_str,
                "moneyness": moneyness,
                "intrinsic_value": intrinsic_value,
                "extrinsic_value": extrinsic_value,
                "mid": close_str,
                "bid": "", "ask": "", "spread": "",
                "implied_volatility": "", "delta": "", "gamma": "", "theta": "", "vega": "",
            })
            written += 1
    except Exception as e:
        logger.warning("    [%s] API error: %s", symbol, e)

    if delay > 0:
        time.sleep(delay)
    return written


def download_ticker(client: RESTClient, ticker: str, year: str, contracts: list[dict],
                    agg: str, output_dir: str | None, delay: float,
                    logger: logging.Logger) -> int:
    underlying_dir = Path(output_dir) / "SPY" / "1min" / year if output_dir else Path("data") / "SPY" / "1min" / year
    underlying_cache = load_underlying_cache(underlying_dir, ticker, year)
    if not underlying_cache:
        logger.warning("  [%s] no underlying OHLCV data for year %s", ticker, year)
        underlying_cache = {}

    proc_path = output_path(ticker, year, agg, output_dir, subdir="processing")
    proc_path.parent.mkdir(parents=True, exist_ok=True)

    file_exists = proc_path.exists() and proc_path.stat().st_size > 0
    mode = "a" if file_exists else "w"
    f = open(proc_path, mode, newline="")
    writer = csv.DictWriter(f, fieldnames=CHAIN_HEADERS)
    if not file_exists:
        writer.writeheader()
        f.flush()

    written = 0
    try:
        for i, contract in enumerate(contracts, 1):
            symbol = contract["contract_symbol"]
            expiry = contract["expiry"]
            from_date = f"{year}-01-01"
            to_date = (expiry + datetime.timedelta(days=1)).isoformat()

            logger.info("    [%d/%d] %s (%s)", i, len(contracts), symbol, expiry)
            contract_written = download_contract_aggs(
                client, contract, from_date, to_date, agg,
                underlying_cache, writer, delay, logger,
            )
            written += contract_written
            f.flush()
    finally:
        f.flush()
        f.close()

    return written


def main():
    args = parse_args()
    overall_start = time.time()

    tickers = load_tickers(args)
    years = (
        [str(y) for y in range(int(args.year.split("-")[0]), int(args.year.split("-")[1]) + 1)]
        if "-" in args.year else [args.year]
    )

    out_dir = args.output
    agg = args.aggregate

    log_base = Path(out_dir) if out_dir else Path("data")
    log_dir = log_base / "options" / "chains" / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    log_ts = datetime.datetime.now().strftime("%Y%m%dT%H%M%S")
    log_path = log_dir / f"{SCRIPT_NAME}_{log_ts}.log"

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[logging.FileHandler(log_path), logging.StreamHandler(sys.stdout)],
    )
    logger = logging.getLogger(SCRIPT_NAME)

    logger.info("Starting options chain download for %d tickers, years=%s", len(tickers), years)
    logger.info("Resume mode: %s", args.resume)

    client = RESTClient(trace=False)
    all_missing = []
    all_results = []
    all_downloaded = 0
    all_skipped = 0

    for year in years:
        downloaded = 0
        skipped = 0
        manifest_path = args.manifest or f"data/options/chains/contract_manifest_{year}.csv"

        for i, ticker in enumerate(tickers, 1):
            if args.resume and is_ticker_complete(ticker, year, agg, out_dir):
                logger.info("[%d/%d] %s (%s) -> already complete, skipping", i, len(tickers), ticker, year)
                skipped += 1
                all_results.append({"ticker": ticker, "year": year, "status": "skipped"})
                continue

            contracts = load_manifest(manifest_path, ticker, year)
            if not contracts:
                logger.info("[%d/%d] %s (%s) -> no contracts in manifest, skipping", i, len(tickers), ticker, year)
                skipped += 1
                all_missing.append(ticker)
                all_results.append({"ticker": ticker, "year": year, "status": "no_contracts"})
                logger.info('PARALLEL_RESULT:{"ticker":"%s","year":"%s","status":"no_contracts","rows":0}', ticker, year)
                sys.stderr.write('PARALLEL_RESULT:{"ticker":"%s","year":"%s","status":"no_contracts","rows":0}\n' % (ticker, year))
                sys.stderr.flush()
                continue

            logger.info("[%d/%d] %s (%s) -> %d contracts ...",
                        i, len(tickers), ticker, year, len(contracts))

            t0 = time.time()
            try:
                count = download_ticker(client, ticker, year, contracts, agg, out_dir, args.delay, logger)
            except Exception as e:
                elapsed = time.time() - t0
                logger.error("[%d/%d] %s (%s) -> FAILED after %.1fs: %s",
                             i, len(tickers), ticker, year, elapsed, e)
                all_missing.append(ticker)
                all_results.append({"ticker": ticker, "year": year, "status": "failed",
                                    "error": str(e), "elapsed_s": round(elapsed, 1)})
                proc_path = output_path(ticker, year, agg, out_dir, subdir="processing")
                if proc_path.exists():
                    err_dir = output_path(ticker, year, agg, out_dir, subdir="errors").parent
                    err_dir.mkdir(parents=True, exist_ok=True)
                    try:
                        proc_path.rename(err_dir / proc_path.name)
                    except OSError:
                        pass
                continue

            elapsed = time.time() - t0

            if count == 0:
                logger.warning("[%d/%d] %s (%s) -> no data returned (%.1fs)",
                               i, len(tickers), ticker, year, elapsed)
                all_missing.append(ticker)
                all_results.append({"ticker": ticker, "year": year, "status": "no_data",
                                    "elapsed_s": round(elapsed, 1)})
                logger.info('PARALLEL_RESULT:{"ticker":"%s","year":"%s","status":"no_data","rows":0}', ticker, year)
                sys.stderr.write('PARALLEL_RESULT:{"ticker":"%s","year":"%s","status":"no_data","rows":0}\n' % (ticker, year))
                sys.stderr.flush()
                proc_path = output_path(ticker, year, agg, out_dir, subdir="processing")
                if proc_path.exists():
                    no_data_dir = output_path(ticker, year, agg, out_dir, subdir="no_data").parent
                    no_data_dir.mkdir(parents=True, exist_ok=True)
                    try:
                        proc_path.rename(no_data_dir / proc_path.name)
                    except OSError:
                        pass
            else:
                proc_path = output_path(ticker, year, agg, out_dir, subdir="processing")
                size = proc_path.stat().st_size
                logger.info("[%d/%d] %s (%s) -> %d rows (%.1fs) -> %s",
                            i, len(tickers), ticker, year, count, elapsed, proc_path)
                downloaded += 1
                all_results.append({
                    "ticker": ticker, "year": year, "status": "ok",
                    "rows": count, "size_bytes": size, "path": str(proc_path),
                    "elapsed_s": round(elapsed, 1),
                })
                logger.info('PARALLEL_RESULT:{"ticker":"%s","year":"%s","status":"ok","rows":%d}',
                            ticker, year, count)
                sys.stderr.write('PARALLEL_RESULT:{"ticker":"%s","year":"%s","status":"ok","rows":%d}\n'
                                 % (ticker, year, count))
                sys.stderr.flush()

        all_downloaded += downloaded
        all_skipped += skipped

    total_time = time.time() - overall_start

    summary = {
        "script": SCRIPT_NAME,
        "timestamp": log_ts,
        "years": years,
        "total_tickers": len(tickers),
        "downloaded": all_downloaded,
        "skipped": all_skipped,
        "missing": sorted(set(all_missing)),
        "missing_count": len(set(all_missing)),
        "duration_s": round(total_time, 1),
        "results": all_results,
    }
    report_path = log_dir / f"{SCRIPT_NAME}_{log_ts}_report.json"
    with open(report_path, "w") as f:
        json.dump(summary, f, indent=2)

    logger.info("=" * 60)
    logger.info("SUMMARY REPORT")
    logger.info("  Duration:       %.1fs", total_time)
    logger.info("  Years:          %s", years)
    logger.info("  Downloaded:     %d", all_downloaded)
    logger.info("  Skipped:        %d", all_skipped)
    logger.info("  Missing/failed: %d", len(set(all_missing)))
    if set(all_missing):
        logger.info("  Missing tickers: %s", ", ".join(sorted(set(all_missing))))
    logger.info("  Report:         %s", report_path)

    if not args.no_rename:
        for year in years:
            for ticker in tickers:
                proc = output_path(ticker, year, agg, out_dir, subdir="processing")
                final = output_path(ticker, year, agg, out_dir)
                if proc.exists() and proc.stat().st_size > 0:
                    final.parent.mkdir(parents=True, exist_ok=True)
                    try:
                        with open(proc) as pf:
                            has_rows = sum(1 for _ in pf) > 1
                        if has_rows:
                            proc.rename(final)
                        else:
                            no_data_dir = output_path(ticker, year, agg, out_dir, subdir="no_data").parent
                            no_data_dir.mkdir(parents=True, exist_ok=True)
                            proc.rename(no_data_dir / proc.name)
                    except OSError:
                        pass


if __name__ == "__main__":
    main()
